services:
  postgres:
    container_name: cookunity-postgres-db-docker
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: cookunity-nest-docker
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - ./src:/app/src

volumes:
  postgres:
